language: csharp
solution: "./DroneProject2.sln"
install:
  - nuget restore "./DroneProject2.sln"
  - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Debug ./DroneProject2.sln